/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.FinanceView;

import javax.swing.*;

/**
 *
 * @author Guy
 */
public class ConfirmPaymentPanel extends JInternalFrame {

    /**
     * Creates new form ConfirmPaymentPanel
     */
    public ConfirmPaymentPanel() {
        super("Confirmar Pagamento",true,true,true,true);
        setLocation(450, 80);
        initComponents();
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PaymentIDLabel = new javax.swing.JLabel();
        PaymentIDTextField = new javax.swing.JTextField();
        ConfirmPaymentButton = new javax.swing.JButton();
        ShowPendingPaymentsPane = new javax.swing.JScrollPane();
        ShowPendingPaymentsTable = new javax.swing.JTable();
        PendingPaymentsLabel = new javax.swing.JLabel();

        PaymentIDLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PaymentIDLabel.setText("ID do Pagamento:");

        PaymentIDTextField.setText("ID");

        ConfirmPaymentButton.setText("Confirmar");

        ShowPendingPaymentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Funcionário", "Cliente", "Data", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ShowPendingPaymentsTable.getTableHeader().setReorderingAllowed(false);
        ShowPendingPaymentsPane.setViewportView(ShowPendingPaymentsTable);

        PendingPaymentsLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PendingPaymentsLabel.setText("Pagamentos Pendentes");

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);

        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PendingPaymentsLabel)
                    .addComponent(ConfirmPaymentButton)
                    .addComponent(ShowPendingPaymentsPane, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PaymentIDLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PaymentIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PaymentIDLabel)
                    .addComponent(PaymentIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ConfirmPaymentButton)
                .addGap(61, 61, 61)
                .addComponent(PendingPaymentsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ShowPendingPaymentsPane, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConfirmPaymentButton;
    private javax.swing.JLabel PaymentIDLabel;
    private javax.swing.JTextField PaymentIDTextField;
    private javax.swing.JLabel PendingPaymentsLabel;
    private javax.swing.JScrollPane ShowPendingPaymentsPane;
    private javax.swing.JTable ShowPendingPaymentsTable;
    // End of variables declaration//GEN-END:variables
}
