/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.FinanceView;

import org.ONE.services.ReservationsServices;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Guy
 */
public class FinanceMainMenu extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FinanceMainMenu.class.getName());
    private final ReservationsServices reservationsServices = new ReservationsServices();

    /*
     * Creates new form FinanceMainMenu
     */
    public FinanceMainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ConfirmQuotaUpdate = new javax.swing.JOptionPane();
        ConfirmQuotaCreated = new javax.swing.JOptionPane();
        ConfirmPayment = new javax.swing.JOptionPane();
        Title = new javax.swing.JLabel();
        UpdatePaymentStatus = new javax.swing.JButton();
        SearchReservations = new javax.swing.JButton();
        ShowQuotas = new javax.swing.JButton();
        ReturnButton = new javax.swing.JButton();
        ParentPanel = new javax.swing.JPanel();
        ReservationStatusPanel = new javax.swing.JPanel();
        PaymentStatusLabel = new javax.swing.JLabel();
        ShowPaymentsPane = new javax.swing.JScrollPane();
        ShowPaymentsTable = new javax.swing.JTable();
        PaymentStatusComboBox = new javax.swing.JComboBox<>();
        QuotasPanel = new javax.swing.JPanel();
        CompanyLabel = new javax.swing.JLabel();
        ShowQuotaCompany = new javax.swing.JLabel();
        EmployeeLabel = new javax.swing.JLabel();
        ShowQuotaEmployee = new javax.swing.JLabel();
        CreateEmployeeQuota = new javax.swing.JLabel();
        CreateEmployeeQuotaBtn = new javax.swing.JButton();
        CreateCompanyQuota = new javax.swing.JLabel();
        CreateCompanyQuotaBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        QuotaContributionTable = new javax.swing.JTable();
        ConfirmPaymentPanel = new javax.swing.JPanel();
        PendingPaymentsPane = new javax.swing.JScrollPane();
        PaymentConfirmationTable = new javax.swing.JTable();
        IDBoxLabel = new javax.swing.JLabel();
        IDBoxTextField = new javax.swing.JTextField();
        IDBoxConfirmButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Finanças");
        setBackground(new java.awt.Color(51, 51, 51));

        Title.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Title.setForeground(new java.awt.Color(51, 51, 51));
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Menu de Finanças");

        UpdatePaymentStatus.setText("Realizar Pagamento");
        UpdatePaymentStatus.addActionListener(this::UpdatePaymentStatusActionPerformed);

        SearchReservations.setText("Buscar Reservas");
        SearchReservations.addActionListener(this::SearchReservationsActionPerformed);

        ShowQuotas.setText("Metas");
        ShowQuotas.addActionListener(this::ShowQuotasActionPerformed);

        ReturnButton.setBackground(new java.awt.Color(51, 51, 51));
        ReturnButton.setText("Voltar");
        ReturnButton.addActionListener(this::ReturnButtonActionPerformed);

        ParentPanel.setLayout(new java.awt.CardLayout());

        PaymentStatusLabel.setBackground(new java.awt.Color(255, 255, 255));
        PaymentStatusLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        PaymentStatusLabel.setForeground(new java.awt.Color(102, 102, 102));
        PaymentStatusLabel.setText("Estado da reserva:");

        ShowPaymentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Valor", "Funcionário", "Cliente", "Data"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ShowPaymentsTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ShowPaymentsPane.setViewportView(ShowPaymentsTable);

        PaymentStatusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "(Selecione)", "Confirmada", "Pendente", "Cancelada" }));

        javax.swing.GroupLayout ReservationStatusPanelLayout = new javax.swing.GroupLayout(ReservationStatusPanel);
        ReservationStatusPanel.setLayout(ReservationStatusPanelLayout);
        ReservationStatusPanelLayout.setHorizontalGroup(
            ReservationStatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReservationStatusPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(ReservationStatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ReservationStatusPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(ShowPaymentsPane, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ReservationStatusPanelLayout.createSequentialGroup()
                        .addComponent(PaymentStatusLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PaymentStatusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        ReservationStatusPanelLayout.setVerticalGroup(
            ReservationStatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReservationStatusPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(ReservationStatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PaymentStatusLabel)
                    .addComponent(PaymentStatusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ShowPaymentsPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        ParentPanel.add(ReservationStatusPanel, "card2");

        CompanyLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CompanyLabel.setText("Meta da Empresa:");

        ShowQuotaCompany.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ShowQuotaCompany.setText("Nenhuma Meta Encontrada");

        EmployeeLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        EmployeeLabel.setText("Meta do Funcionário:");

        ShowQuotaEmployee.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ShowQuotaEmployee.setText("Nenhuma Meta Encontrada");

        CreateEmployeeQuota.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CreateEmployeeQuota.setText("Criar Meta Pessoal:");

        CreateEmployeeQuotaBtn.setText("Criar");

        CreateCompanyQuota.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CreateCompanyQuota.setText("Criar Meta Empresa:");

        CreateCompanyQuotaBtn.setText("Criar");

        QuotaContributionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Pagamento", "Status"
            }
        ));
        jScrollPane1.setViewportView(QuotaContributionTable);

        javax.swing.GroupLayout QuotasPanelLayout = new javax.swing.GroupLayout(QuotasPanel);
        QuotasPanel.setLayout(QuotasPanelLayout);
        QuotasPanelLayout.setHorizontalGroup(
            QuotasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuotasPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(QuotasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(QuotasPanelLayout.createSequentialGroup()
                        .addGroup(QuotasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(QuotasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(EmployeeLabel)
                                .addComponent(CompanyLabel))
                            .addGroup(QuotasPanelLayout.createSequentialGroup()
                                .addComponent(CreateEmployeeQuota)
                                .addGap(27, 27, 27)))
                        .addGroup(QuotasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(QuotasPanelLayout.createSequentialGroup()
                                .addGroup(QuotasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ShowQuotaEmployee, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ShowQuotaCompany, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE))
                            .addGroup(QuotasPanelLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(CreateEmployeeQuotaBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(12, 12, 12))))
                    .addGroup(QuotasPanelLayout.createSequentialGroup()
                        .addComponent(CreateCompanyQuota)
                        .addGap(32, 32, 32)
                        .addComponent(CreateCompanyQuotaBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(12, 12, 12)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        QuotasPanelLayout.setVerticalGroup(
            QuotasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuotasPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(QuotasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmployeeLabel)
                    .addComponent(ShowQuotaEmployee))
                .addGap(6, 6, 6)
                .addGroup(QuotasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ShowQuotaCompany)
                    .addComponent(CompanyLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(QuotasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CreateCompanyQuota)
                    .addComponent(CreateCompanyQuotaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(QuotasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CreateEmployeeQuota)
                    .addComponent(CreateEmployeeQuotaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(179, 179, 179))
            .addGroup(QuotasPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        ParentPanel.add(QuotasPanel, "card3");

        PaymentConfirmationTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome Cliente", "Valor", "Data"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        PendingPaymentsPane.setViewportView(PaymentConfirmationTable);

        IDBoxLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        IDBoxLabel.setText("ID do Pagamento:");

        IDBoxTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        IDBoxTextField.setText("ID");

        IDBoxConfirmButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        IDBoxConfirmButton.setText("Confirmar");
        IDBoxConfirmButton.addActionListener(this::IDBoxConfirmButtonActionPerformed);

        javax.swing.GroupLayout ConfirmPaymentPanelLayout = new javax.swing.GroupLayout(ConfirmPaymentPanel);
        ConfirmPaymentPanel.setLayout(ConfirmPaymentPanelLayout);
        ConfirmPaymentPanelLayout.setHorizontalGroup(
            ConfirmPaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ConfirmPaymentPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(ConfirmPaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IDBoxLabel)
                    .addGroup(ConfirmPaymentPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(ConfirmPaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IDBoxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IDBoxConfirmButton))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(PendingPaymentsPane, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ConfirmPaymentPanelLayout.setVerticalGroup(
            ConfirmPaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConfirmPaymentPanelLayout.createSequentialGroup()
                .addGroup(ConfirmPaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ConfirmPaymentPanelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(PendingPaymentsPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ConfirmPaymentPanelLayout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(IDBoxLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(IDBoxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IDBoxConfirmButton)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        ParentPanel.add(ConfirmPaymentPanel, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Title))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UpdatePaymentStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SearchReservations, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ShowQuotas, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ReturnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(643, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(211, 211, 211)
                    .addComponent(ParentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(Title)
                .addGap(54, 54, 54)
                .addComponent(UpdatePaymentStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(SearchReservations, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(ShowQuotas, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(ReturnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(ParentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void SearchReservationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchReservationsActionPerformed
        ((java.awt.CardLayout) ParentPanel.getLayout()).show(ParentPanel, "card2");
    }//GEN-LAST:event_SearchReservationsActionPerformed

    private void ShowQuotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowQuotasActionPerformed
        ((java.awt.CardLayout) ParentPanel.getLayout()).show(ParentPanel, "card3");
    }//GEN-LAST:event_ShowQuotasActionPerformed

    private void UpdatePaymentStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatePaymentStatusActionPerformed
        ((java.awt.CardLayout) ParentPanel.getLayout()).show(ParentPanel, "card4");
    }//GEN-LAST:event_UpdatePaymentStatusActionPerformed

    private void ReturnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnButtonActionPerformed
        
    }//GEN-LAST:event_ReturnButtonActionPerformed

    private void IDBoxConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDBoxConfirmButtonActionPerformed
        //TODO:
    }//GEN-LAST:event_IDBoxConfirmButtonActionPerformed

    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FinanceMainMenu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CompanyLabel;
    private javax.swing.JOptionPane ConfirmPayment;
    private javax.swing.JPanel ConfirmPaymentPanel;
    private javax.swing.JOptionPane ConfirmQuotaCreated;
    private javax.swing.JOptionPane ConfirmQuotaUpdate;
    private javax.swing.JLabel CreateCompanyQuota;
    private javax.swing.JButton CreateCompanyQuotaBtn;
    private javax.swing.JLabel CreateEmployeeQuota;
    private javax.swing.JButton CreateEmployeeQuotaBtn;
    private javax.swing.JLabel EmployeeLabel;
    private javax.swing.JButton IDBoxConfirmButton;
    private javax.swing.JLabel IDBoxLabel;
    private javax.swing.JTextField IDBoxTextField;
    private javax.swing.JPanel ParentPanel;
    private javax.swing.JTable PaymentConfirmationTable;
    private javax.swing.JComboBox<String> PaymentStatusComboBox;
    private javax.swing.JLabel PaymentStatusLabel;
    private javax.swing.JScrollPane PendingPaymentsPane;
    private javax.swing.JTable QuotaContributionTable;
    private javax.swing.JPanel QuotasPanel;
    private javax.swing.JPanel ReservationStatusPanel;
    private javax.swing.JButton ReturnButton;
    private javax.swing.JButton SearchReservations;
    private javax.swing.JScrollPane ShowPaymentsPane;
    private javax.swing.JTable ShowPaymentsTable;
    private javax.swing.JLabel ShowQuotaCompany;
    private javax.swing.JLabel ShowQuotaEmployee;
    private javax.swing.JButton ShowQuotas;
    private javax.swing.JLabel Title;
    private javax.swing.JButton UpdatePaymentStatus;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
