/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.FinanceView;

/**
 *
 * @author Guy
 */
public class QuotasPanel extends javax.swing.JPanel {

    /**
     * Creates new form QuotasPanel
     */
    public QuotasPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CompanyQuotaLabel = new javax.swing.JLabel();
        EmployeeQuotaLabel = new javax.swing.JLabel();
        ShowCompanyQuotaPane = new javax.swing.JScrollPane();
        ShowCompanyQuotaTextPanel = new javax.swing.JTextPane();
        ShowEmployeeQuotaPane = new javax.swing.JScrollPane();
        ShowEmployeeQuotaTextPanel = new javax.swing.JTextPane();
        CreateEmployeeQuotaLabel = new javax.swing.JLabel();
        CreateCompanyQuotaLabel = new javax.swing.JLabel();
        CreatePersonalQuota = new javax.swing.JButton();
        CreateCompanyQuota = new javax.swing.JButton();
        ShowContributingValuesPanel = new javax.swing.JScrollPane();
        ShowContributingValues = new javax.swing.JTable();

        CompanyQuotaLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CompanyQuotaLabel.setText("Meta da Empresa:");

        EmployeeQuotaLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EmployeeQuotaLabel.setText("Meta Pessoal:");

        ShowCompanyQuotaPane.setViewportView(ShowCompanyQuotaTextPanel);

        ShowEmployeeQuotaPane.setViewportView(ShowEmployeeQuotaTextPanel);

        CreateEmployeeQuotaLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CreateEmployeeQuotaLabel.setText("Criar Meta Pessoal");

        CreateCompanyQuotaLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CreateCompanyQuotaLabel.setText("Criar Meta da Empresa");

        CreatePersonalQuota.setText("Criar");

        CreateCompanyQuota.setText("Criar");

        ShowContributingValues.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID da Reserva", "ShowContributingValues"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ShowContributingValues.getTableHeader().setReorderingAllowed(false);
        ShowContributingValuesPanel.setViewportView(ShowContributingValues);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CreateCompanyQuotaLabel)
                        .addGap(18, 18, 18)
                        .addComponent(CreateCompanyQuota))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CompanyQuotaLabel)
                            .addComponent(EmployeeQuotaLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ShowCompanyQuotaPane, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(ShowEmployeeQuotaPane)))
                    .addComponent(ShowContributingValuesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CreateEmployeeQuotaLabel)
                        .addGap(44, 44, 44)
                        .addComponent(CreatePersonalQuota)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CompanyQuotaLabel)
                    .addComponent(ShowCompanyQuotaPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ShowEmployeeQuotaPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmployeeQuotaLabel))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CreateEmployeeQuotaLabel)
                    .addComponent(CreatePersonalQuota))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CreateCompanyQuotaLabel)
                    .addComponent(CreateCompanyQuota))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(ShowContributingValuesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CompanyQuotaLabel;
    private javax.swing.JButton CreateCompanyQuota;
    private javax.swing.JLabel CreateCompanyQuotaLabel;
    private javax.swing.JLabel CreateEmployeeQuotaLabel;
    private javax.swing.JButton CreatePersonalQuota;
    private javax.swing.JLabel EmployeeQuotaLabel;
    private javax.swing.JScrollPane ShowCompanyQuotaPane;
    private javax.swing.JTextPane ShowCompanyQuotaTextPanel;
    private javax.swing.JTable ShowContributingValues;
    private javax.swing.JScrollPane ShowContributingValuesPanel;
    private javax.swing.JScrollPane ShowEmployeeQuotaPane;
    private javax.swing.JTextPane ShowEmployeeQuotaTextPanel;
    // End of variables declaration//GEN-END:variables
}
